# Generated by Django 5.0.3 on 2024-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=10, unique=True)),
                ('guests_name', models.CharField(max_length=100)),
                ('guests_surname', models.CharField(max_length=100)),
                ('guests_email', models.EmailField(max_length=254)),
                ('guests_phone', models.CharField(max_length=100)),
                ('guest_checkin', models.DateField()),
                ('guest_checkout', models.DateField()),
                ('guests_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
