# Generated by Django 5.0.2 on 2024-04-28 21:13

import Reception.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('encounter_hour', models.TimeField(default=Reception.models.get_current_date)),
                ('encounter_date', models.DateField(default=Reception.models.get_current_date)),
                ('in_possesion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('is_clean', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='room_photos/')),
                ('description', models.TextField()),
                ('square_meter', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=100)),
                ('guests_name', models.CharField(max_length=100)),
                ('guests_surname', models.CharField(max_length=100)),
                ('guests_email', models.EmailField(max_length=254)),
                ('guests_phone', models.CharField(max_length=100)),
                ('guest_checkin', models.DateField(blank=True, null=True)),
                ('guest_checkout', models.DateField(blank=True, null=True)),
                ('guest_checkin_hour', models.TimeField(default=datetime.time(13, 0))),
                ('guest_checkout_hour', models.TimeField(default=datetime.time(10, 0))),
                ('guest_is_here', models.BooleanField(default=False)),
                ('guests_number', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('room_is_payed', models.BooleanField(default=False)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.room')),
            ],
        ),
    ]
