# Generated by Django 5.0.2 on 2024-04-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='DNI',
            field=models.CharField(max_length=10),
        ),
    ]
