# Generated by Django 5.0.3 on 2024-03-27 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='room_photos/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='test',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Reception.roomtype'),
            preserve_default=False,
        ),
    ]
