# Generated by Django 5.0.2 on 2024-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='square_meter',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
