# Generated by Django 5.0.2 on 2024-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='guests_number',
            field=models.IntegerField(default=0),
        ),
    ]
