# Generated by Django 5.0.4 on 2024-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='DNI',
            field=models.CharField(max_length=10),
        ),
    ]
