# Generated by Django 5.0.2 on 2024-06-13 16:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='item_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identifier', models.CharField(default='0000A', max_length=5)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('entrance_hours', models.TimeField()),
                ('date_entrance', models.DateField()),
                ('costumers_number', models.IntegerField(default=0)),
                ('validated', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('order_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.order')),
                ('room_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
    ]
