# Generated by Django 5.0.3 on 2024-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_names', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=100)),
                ('number_guests', models.IntegerField(default=0)),
                ('date_reservation', models.DateField()),
            ],
        ),
    ]
