# Generated by Django 5.0.4 on 2024-04-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0002_alter_roomreservation_dni'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReservation_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('entrance_hours', models.IntegerField(default=0)),
                ('date_entrance', models.DateField()),
                ('costumers_number', models.IntegerField(default=0)),
                ('room_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reception.roomreservation')),
            ],
        ),
    ]
