# Generated by Django 5.0.4 on 2024-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_restaurantreservation_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreservation_v2',
            name='entrance_hours',
            field=models.TimeField(),
        ),
    ]
