# Generated by Django 5.0.2 on 2024-03-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=50)),
                ('shift', models.DateTimeField()),
            ],
        ),
    ]
