#name: Playwright Tests
#on:
#  push:
#    branches: [ main, master, dev ]
#  pull_request:
#    branches: [ main, master, dev ]
#jobs:
#  test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.11'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: Ensure browsers are installed
#      run: python manage.py runserver & python -m playwright install --with-deps
#    - name: Run your tests
#      run: pytest --tracing=retain-on-failure
#    - uses: actions/upload-artifact@v4
#      if: ${{ !cancelled() }}
#      with:
#        name: playwright-traces
#        path: test-results/
